doctrine:
  dbal:
    url: 'postgresql://%env(POSTGRES_USER)%:%env(POSTGRES_PASSWORD)%@%env(POSTGRES_HOST)%:%env(POSTGRES_PORT)%/%env(POSTGRES_DB)%?serverVersion=17&charset=utf8'
    profiling_collect_backtrace: '%kernel.debug%'
    use_savepoints: true
