services:

  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app:cached
    ports:
      - "80:80"
