services:

  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app:cached
    ports:
      - "${DOCKER_PHP_EXTERNAL_PORT:-80}:${DOCKER_PHP_INTERNAL_PORT:-80}"
    depends_on:
      - mysql
      - postgres

  mysql:
    image: mariadb:10.8.2
    restart: always
    env_file:
      - .env
      - .env.local
    ports:
      - "${DOCKER_MYSQL_EXTERNAL_PORT:-3306}:${DOCKER_MYSQL_INTERNAL_PORT:-3306}"

  postgres:
    image: postgres:16.4-alpine3.20
    restart: always
    env_file:
      - .env
      - .env.local
    ports:
      - "${DOCKER_POSTGRES_EXTERNAL_PORT:-5432}:${DOCKER_POSTGRES_INTERNAL_PORT:-5432}"
