services:

  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app:cached
    ports:
      - "80:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    env_file:
      - .env
      - .env.local
    volumes:
      - ./var/postgres/:/var/lib/postgresql/data/:cached
    ports:
      - "5432:5432"
