services:

  php:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app:cached
    ports:
      - "${DOCKER_PHP_EXTERNAL_PORT:-80}:${DOCKER_PHP_INTERNAL_PORT:-80}"
